development:
    adapter: postgresql
    encoding: unicode
    database: winseDecor_development
    username: slyman
    password: 
    host: localhost
    port: 5432
	
production:
    adapter: postgresql
    encoding: unicode
    database: winseDecor_production
    username: slyman
    password: 
    host: localhost
    port: 5432
